### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Treri/fzf-zsh#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by ik0r** [comment]
@unixorn ok, I will add MIT license

**Comment by unixorn** [comment]
Thanks, added in https://github.com/unixorn/awesome-zsh-plugins/pull/770
